import React from 'react';
import './PolicyPages.css'; // Import the shared CSS

const TermsOfService = () => {
  return (
    <div className="policy-page">
      <h1>Terms of Service</h1>
      <em className="last-updated">Last updated: October 22, 2025</em>

      <p>Please read these Terms of Service ("Terms") carefully before using the PlantGuard AI application (the "Service"). Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms.</p>

      <h2>1. Acceptance of Terms</h2>
      <p>By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.</p>

      <h2>2. Description of Service</h2>
      <p>PlantGuard AI provides an image analysis tool intended to identify potential plant diseases based on user-submitted images. The results are generated by an artificial intelligence model and are provided for <strong>informational purposes only</strong>. The Service does not provide definitive diagnoses or professional agricultural advice.</p>

      <h2>3. Use License</h2>
      <p>Permission is granted to temporarily use the Service for personal, non-commercial transitory viewing only. You may not:</p>
      <ul>
        <li>Modify or copy the materials;</li>
        <li>Use the materials for any commercial purpose;</li>
        <li>Attempt to decompile or reverse engineer any software contained within the Service;</li>
        <li>Remove any copyright or other proprietary notations from the materials.</li>
      </ul>

      <h2>4. Disclaimer of Warranties</h2>
      <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. PlantGuard AI makes no warranties, expressed or implied, and hereby disclaims all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement. We do not guarantee the accuracy, completeness, or usefulness of the information provided.</p>
      <p><strong>Always consult with a qualified professional (e.g., agricultural extension agent, certified arborist) for definitive plant health advice and treatment decisions.</strong></p>

      <h2>5. Limitation of Liability</h2>
      <p>In no event shall PlantGuard AI or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the Service, even if notified orally or in writing of the possibility of such damage.</p>

      <h2>6. Modifications</h2>
      <p>We may revise these Terms of Service at any time without notice. By using this Service you are agreeing to be bound by the then current version of these Terms.</p>

      <h2>7. Governing Law</h2>
      <p>Any claim relating to the Service shall be governed by the laws of [Your Jurisdiction - e.g., State of Karnataka, India] without regard to its conflict of law provisions.</p>

      <h2>8. Contact Us</h2>
      <p>If you have any questions about these Terms, please contact us via the form on our Contact page.</p>

      <div className="disclaimer-note">
        <p><strong>IMPORTANT DISCLAIMER:</strong> This is sample placeholder text. It is NOT a legally binding Terms of Service agreement. You MUST consult with a qualified legal professional to draft Terms that are legally sound, protect your interests, and are appropriate for your specific application, jurisdiction, and potential liabilities.</p>
      </div>
    </div>
  );
};

export default TermsOfService;